/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DebateRouteImport } from './routes/debate'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResultRouteImport } from './routes/result'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiSessionRouteImport } from './routes/api/session'
import { Route as TrainIndexRouteImport } from './routes/train.index'
import { Route as TrainModeRouteImport } from './routes/train.$mode'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DebateRoute = DebateRouteImport.update({
  id: '/debate',
  path: '/debate',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionRoute = ApiSessionRouteImport.update({
  id: '/api/session',
  path: '/api/session',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainIndexRoute = TrainIndexRouteImport.update({
  id: '/train/',
  path: '/train/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainModeRoute = TrainModeRouteImport.update({
  id: '/train/$mode',
  path: '/train/$mode',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/debate': typeof DebateRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/result': typeof ResultRoute
  '/signup': typeof SignupRoute
  '/api/chat': typeof ApiChatRoute
  '/api/session': typeof ApiSessionRoute
  '/train/$mode': typeof TrainModeRoute
  '/train/': typeof TrainIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/debate': typeof DebateRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/result': typeof ResultRoute
  '/signup': typeof SignupRoute
  '/api/chat': typeof ApiChatRoute
  '/api/session': typeof ApiSessionRoute
  '/train/$mode': typeof TrainModeRoute
  '/train': typeof TrainIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/debate': typeof DebateRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/result': typeof ResultRoute
  '/signup': typeof SignupRoute
  '/api/chat': typeof ApiChatRoute
  '/api/session': typeof ApiSessionRoute
  '/train/$mode': typeof TrainModeRoute
  '/train/': typeof TrainIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/debate'
    | '/login'
    | '/profile'
    | '/result'
    | '/signup'
    | '/api/chat'
    | '/api/session'
    | '/train/$mode'
    | '/train/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/debate'
    | '/login'
    | '/profile'
    | '/result'
    | '/signup'
    | '/api/chat'
    | '/api/session'
    | '/train/$mode'
    | '/train'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/debate'
    | '/login'
    | '/profile'
    | '/result'
    | '/signup'
    | '/api/chat'
    | '/api/session'
    | '/train/$mode'
    | '/train/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DebateRoute: typeof DebateRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ResultRoute: typeof ResultRoute
  SignupRoute: typeof SignupRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiSessionRoute: typeof ApiSessionRoute
  TrainModeRoute: typeof TrainModeRoute
  TrainIndexRoute: typeof TrainIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debate': {
      id: '/debate'
      path: '/debate'
      fullPath: '/debate'
      preLoaderRoute: typeof DebateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session': {
      id: '/api/session'
      path: '/api/session'
      fullPath: '/api/session'
      preLoaderRoute: typeof ApiSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/train/': {
      id: '/train/'
      path: '/train'
      fullPath: '/train/'
      preLoaderRoute: typeof TrainIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/train/$mode': {
      id: '/train/$mode'
      path: '/train/$mode'
      fullPath: '/train/$mode'
      preLoaderRoute: typeof TrainModeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DebateRoute: DebateRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ResultRoute: ResultRoute,
  SignupRoute: SignupRoute,
  ApiChatRoute: ApiChatRoute,
  ApiSessionRoute: ApiSessionRoute,
  TrainModeRoute: TrainModeRoute,
  TrainIndexRoute: TrainIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
