/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as CaseDiscussionRouteImport } from './routes/case-discussion'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DebateRouteImport } from './routes/debate'
import { Route as EvaluationRouteImport } from './routes/evaluation'
import { Route as ExtemporeRouteImport } from './routes/extempore'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as GroupDiscussionRouteImport } from './routes/group-discussion'
import { Route as InterviewRouteImport } from './routes/interview'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NegotiationRouteImport } from './routes/negotiation'
import { Route as ObserverRouteImport } from './routes/observer'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PublicSpeakingRouteImport } from './routes/public-speaking'
import { Route as ResultRouteImport } from './routes/result'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SimulationRouteImport } from './routes/simulation'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiSessionRouteImport } from './routes/api/session'
import { Route as TrainIndexRouteImport } from './routes/train.index'
import { Route as TrainModeRouteImport } from './routes/train.$mode'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseDiscussionRoute = CaseDiscussionRouteImport.update({
  id: '/case-discussion',
  path: '/case-discussion',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DebateRoute = DebateRouteImport.update({
  id: '/debate',
  path: '/debate',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationRoute = EvaluationRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtemporeRoute = ExtemporeRouteImport.update({
  id: '/extempore',
  path: '/extempore',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupDiscussionRoute = GroupDiscussionRouteImport.update({
  id: '/group-discussion',
  path: '/group-discussion',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewRoute = InterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NegotiationRoute = NegotiationRouteImport.update({
  id: '/negotiation',
  path: '/negotiation',
  getParentRoute: () => rootRouteImport,
} as any)
const ObserverRoute = ObserverRouteImport.update({
  id: '/observer',
  path: '/observer',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicSpeakingRoute = PublicSpeakingRouteImport.update({
  id: '/public-speaking',
  path: '/public-speaking',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationRoute = SimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionRoute = ApiSessionRouteImport.update({
  id: '/api/session',
  path: '/api/session',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainIndexRoute = TrainIndexRouteImport.update({
  id: '/train/',
  path: '/train/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainModeRoute = TrainModeRouteImport.update({
  id: '/train/$mode',
  path: '/train/$mode',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/analytics': typeof AnalyticsRoute
  '/case-discussion': typeof CaseDiscussionRoute
  '/dashboard': typeof DashboardRoute
  '/debate': typeof DebateRoute
  '/evaluation': typeof EvaluationRoute
  '/extempore': typeof ExtemporeRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/group-discussion': typeof GroupDiscussionRoute
  '/interview': typeof InterviewRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/negotiation': typeof NegotiationRoute
  '/observer': typeof ObserverRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/public-speaking': typeof PublicSpeakingRoute
  '/result': typeof ResultRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/simulation': typeof SimulationRoute
  '/api/chat': typeof ApiChatRoute
  '/api/session': typeof ApiSessionRoute
  '/train/$mode': typeof TrainModeRoute
  '/train/': typeof TrainIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/analytics': typeof AnalyticsRoute
  '/case-discussion': typeof CaseDiscussionRoute
  '/dashboard': typeof DashboardRoute
  '/debate': typeof DebateRoute
  '/evaluation': typeof EvaluationRoute
  '/extempore': typeof ExtemporeRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/group-discussion': typeof GroupDiscussionRoute
  '/interview': typeof InterviewRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/negotiation': typeof NegotiationRoute
  '/observer': typeof ObserverRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/public-speaking': typeof PublicSpeakingRoute
  '/result': typeof ResultRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/simulation': typeof SimulationRoute
  '/api/chat': typeof ApiChatRoute
  '/api/session': typeof ApiSessionRoute
  '/train/$mode': typeof TrainModeRoute
  '/train': typeof TrainIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/analytics': typeof AnalyticsRoute
  '/case-discussion': typeof CaseDiscussionRoute
  '/dashboard': typeof DashboardRoute
  '/debate': typeof DebateRoute
  '/evaluation': typeof EvaluationRoute
  '/extempore': typeof ExtemporeRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/group-discussion': typeof GroupDiscussionRoute
  '/interview': typeof InterviewRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/negotiation': typeof NegotiationRoute
  '/observer': typeof ObserverRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/public-speaking': typeof PublicSpeakingRoute
  '/result': typeof ResultRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/simulation': typeof SimulationRoute
  '/api/chat': typeof ApiChatRoute
  '/api/session': typeof ApiSessionRoute
  '/train/$mode': typeof TrainModeRoute
  '/train/': typeof TrainIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/analytics'
    | '/case-discussion'
    | '/dashboard'
    | '/debate'
    | '/evaluation'
    | '/extempore'
    | '/forgot-password'
    | '/group-discussion'
    | '/interview'
    | '/leaderboard'
    | '/login'
    | '/negotiation'
    | '/observer'
    | '/pricing'
    | '/profile'
    | '/public-speaking'
    | '/result'
    | '/settings'
    | '/signup'
    | '/simulation'
    | '/api/chat'
    | '/api/session'
    | '/train/$mode'
    | '/train/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/analytics'
    | '/case-discussion'
    | '/dashboard'
    | '/debate'
    | '/evaluation'
    | '/extempore'
    | '/forgot-password'
    | '/group-discussion'
    | '/interview'
    | '/leaderboard'
    | '/login'
    | '/negotiation'
    | '/observer'
    | '/pricing'
    | '/profile'
    | '/public-speaking'
    | '/result'
    | '/settings'
    | '/signup'
    | '/simulation'
    | '/api/chat'
    | '/api/session'
    | '/train/$mode'
    | '/train'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/analytics'
    | '/case-discussion'
    | '/dashboard'
    | '/debate'
    | '/evaluation'
    | '/extempore'
    | '/forgot-password'
    | '/group-discussion'
    | '/interview'
    | '/leaderboard'
    | '/login'
    | '/negotiation'
    | '/observer'
    | '/pricing'
    | '/profile'
    | '/public-speaking'
    | '/result'
    | '/settings'
    | '/signup'
    | '/simulation'
    | '/api/chat'
    | '/api/session'
    | '/train/$mode'
    | '/train/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CaseDiscussionRoute: typeof CaseDiscussionRoute
  DashboardRoute: typeof DashboardRoute
  DebateRoute: typeof DebateRoute
  EvaluationRoute: typeof EvaluationRoute
  ExtemporeRoute: typeof ExtemporeRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GroupDiscussionRoute: typeof GroupDiscussionRoute
  InterviewRoute: typeof InterviewRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  NegotiationRoute: typeof NegotiationRoute
  ObserverRoute: typeof ObserverRoute
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRoute
  PublicSpeakingRoute: typeof PublicSpeakingRoute
  ResultRoute: typeof ResultRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SimulationRoute: typeof SimulationRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiSessionRoute: typeof ApiSessionRoute
  TrainModeRoute: typeof TrainModeRoute
  TrainIndexRoute: typeof TrainIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-discussion': {
      id: '/case-discussion'
      path: '/case-discussion'
      fullPath: '/case-discussion'
      preLoaderRoute: typeof CaseDiscussionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debate': {
      id: '/debate'
      path: '/debate'
      fullPath: '/debate'
      preLoaderRoute: typeof DebateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation': {
      id: '/evaluation'
      path: '/evaluation'
      fullPath: '/evaluation'
      preLoaderRoute: typeof EvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extempore': {
      id: '/extempore'
      path: '/extempore'
      fullPath: '/extempore'
      preLoaderRoute: typeof ExtemporeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group-discussion': {
      id: '/group-discussion'
      path: '/group-discussion'
      fullPath: '/group-discussion'
      preLoaderRoute: typeof GroupDiscussionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview': {
      id: '/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof InterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/negotiation': {
      id: '/negotiation'
      path: '/negotiation'
      fullPath: '/negotiation'
      preLoaderRoute: typeof NegotiationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observer': {
      id: '/observer'
      path: '/observer'
      fullPath: '/observer'
      preLoaderRoute: typeof ObserverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public-speaking': {
      id: '/public-speaking'
      path: '/public-speaking'
      fullPath: '/public-speaking'
      preLoaderRoute: typeof PublicSpeakingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulation': {
      id: '/simulation'
      path: '/simulation'
      fullPath: '/simulation'
      preLoaderRoute: typeof SimulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session': {
      id: '/api/session'
      path: '/api/session'
      fullPath: '/api/session'
      preLoaderRoute: typeof ApiSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/train/': {
      id: '/train/'
      path: '/train'
      fullPath: '/train/'
      preLoaderRoute: typeof TrainIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/train/$mode': {
      id: '/train/$mode'
      path: '/train/$mode'
      fullPath: '/train/$mode'
      preLoaderRoute: typeof TrainModeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  AnalyticsRoute: AnalyticsRoute,
  CaseDiscussionRoute: CaseDiscussionRoute,
  DashboardRoute: DashboardRoute,
  DebateRoute: DebateRoute,
  EvaluationRoute: EvaluationRoute,
  ExtemporeRoute: ExtemporeRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GroupDiscussionRoute: GroupDiscussionRoute,
  InterviewRoute: InterviewRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  NegotiationRoute: NegotiationRoute,
  ObserverRoute: ObserverRoute,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRoute,
  PublicSpeakingRoute: PublicSpeakingRoute,
  ResultRoute: ResultRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SimulationRoute: SimulationRoute,
  ApiChatRoute: ApiChatRoute,
  ApiSessionRoute: ApiSessionRoute,
  TrainModeRoute: TrainModeRoute,
  TrainIndexRoute: TrainIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
